print('[x2:]')
print('Now watch me whip')
print('Watch me nae nae')
print('Now watch me whip whip')
print('Watch me nae nae')
print()
print('[x2:]')
print('Ooh watch me, watch me')
print('Ooh watch me, watch me')
print('Ooh watch me, watch me')
print('Ooh ooh ooh ooh')
print()

print('Now watch me you')
print('Now watch me superman')
print('Now watch me you')
print('Now watch me superman')
print()

print('[x2:]')
print('Do the stanky leg')
print('Do the stanky leg')
print()

print('[x2:]')
print('Now watch me')
print('Bop bop bop bop bop bop bop bop bop')
print()

print('[x2:]')
print('Now watch me whip')
print('Watch me nae nae')
print('Now watch me whip whip')
print('Watch me nae nae')
print()
print('[x2:]')
print('Ooh watch me, watch me')
print('Ooh watch me, watch me')
print('Ooh watch me, watch me')
print('Ooh ooh ooh ooh')
print()

print('Now watch me you')
print('Now watch me superman')
print('Now watch me you')
print('Now watch me superman')
print()

print('[x4:]')
print('Now break your legs')
print('Break your legs')
print()

print('[x2:]')
print('Now watch me')
print('Bop bop bop bop bop bop bop bop bop')
print()

print('[x2:]')
print('Now watch me whip')
print('Watch me nae nae')
print('Now watch me whip whip')
print('Watch me nae nae')
print()
print('[x2:]')
print('Ooh watch me, watch me')
print('Ooh watch me, watch me')
print('Ooh watch me, watch me')
print('Ooh ooh ooh ooh')
print()

print('Crank dat')